name: units
parameters: |
  __spring.xml=unit/apistats.xml
children:
  - name: rpc_executor
  - name: interact_features.logging
    parameters: |
      name=logging
    children:
      - name: feature_logging
  - name: rxretry.default
    parameters: |
      name=retry.default
      exception=java.net.ConnectException
      retryinterval = 10000
  - name: rxtimeout.default
    parameters: |
      name=timeout.default
      timeout.ms = 15000
  - name: rpcs_top.global
    parameters: |
      before = logging
      after = retry.default, timeout.default
  - name: rpcs_top.org.jocean.restfuldemo.ctrl.DemoController
    parameters: |
      name=org.jocean.restfuldemo.ctrl.DemoController
      before = 
      after = 
    children:
      - name: rpcs_sub.getCityByIpV2
        parameters: |
          name= getCityByIpV2
          before = logging
          after = retry.default, timeout.default
  - name: nettystats
  - name: jolokia
    parameters: |
      jolokia.port = 3020
  - name: jmxsrv
    parameters: |
      jmxmp.port = 0
      jmxhtml.port = 7321
  - name: service
    parameters: |
      demo.action=hi
  - name: hystrixstream
  - name: statrest
  - name: cors
  - name: logrest
  - name: 100continue
  - name: ctrl
  - name: prometheus_jmx_exporter
    parameters: |
      ## yaml
      
      config: |
        lowercaseOutputName: true
        lowercaseOutputLabelNames: true
        attrNameSnakeCase: true
        whitelistObjectNames: ["java.*:*"]
        rules:
        - pattern: ".*"
  - name: export_prometheus.default
  - name: httpclient.default
  - name: httpserver
    parameters: |
      # set recv buffer size 8k
      http.server.inbound.recvbuf = 8192
      
      # work thread count
      http.server.work.thread.count=2
    children:
      - name: restin.9090
        parameters: |
          http.port = 9090
          http.address=0.0.0.0
          restin.pathpattern=/newrest/|/hystrix.stream
          restin.category = demo
        children:
          - name: feature_logging
          - name: set_interceptor.demo
            parameters: |
              # Resource Class
              resource.class=org.jocean.restfuldemo.ctrl.DemoController
              # interceptors (full class name) to attach
              resource.interceptors=\
              org.jocean.svr.interceptor.StatRest,\
              org.jocean.svr.interceptor.LogRest,\
              org.jocean.svr.interceptor.EnableCORS
      - name: restin.8080
        parameters: |
          http.port = 8080
          http.address=0.0.0.0
          restin.pathpattern=^/metrics
          restin.category = not_exist
        children:
          - name: feature_logging
          - name: feature_compress
              