name: units
parameters: |
  __spring.xml=http/httpserver.xml,jocean/eventengine.xml,http/httpclient.xml,http/signal.xml,unit/flowstats.xml
children:
  - name: jolokia
    parameters: |
      jolokia.port = 3020
  - name: jmxsrv
    parameters: |
      jmxmp.port = 0
      jmxhtml.port = 7321
  - name: httpinbound.8080
    parameters: |
      http.port = 8080
      http.address=0.0.0.0
      inbound.pathpattern=/welcome/[{|}|/|\\w]*
      inbound.category=demo
    children:
      - name: feature_logging
  - name: regsignal_embed.outbound
    parameters: |
      req.class =org.jocean.restfuldemo.bean.outbound.OutboundRequest
      resp.class=org.jocean.restfuldemo.bean.outbound.OutboundResponse
      signal.uri=http://api.huaban.com
    children:
      - name: feature_logging
  - name: flowdemo
    parameters: |
      wechat.redirecturi=http://www.baidu.com/
      alipay.redirecturi=https://qr.alipay.com/ppx01048optiqycgvvhwpfc?q=1
  - name: service
    parameters: |
      demo.action=hi
      