name: units
parameters: |
  __spring.xml=unit/apistats.xml
children:
  - name: lbsyunapi.smt
    parameters: |
      api.baiduak=xxxxxx
  - name: interact_features.logging
    parameters: |
      name=logging
    children:
      - name: feature_logging
  - name: rxretry.default
    parameters: |
      name=retry.default
      exception=java.net.ConnectException
      retryinterval = 10000
  - name: rxtimeout.default
    parameters: |
      name=timeout.default
      timeout.ms = 15000
  #- name: redisclient
  #  parameters: |
  #    redis.server.hostname=localhost
  #    redis.server.port=6379
  #    redis.server.passwd=passwd
  #    redis.server.dbno=255
  - name: rpcs_top.global
    parameters: |
      before = logging
      after = retry.default, timeout.default
  - name: rpcs_top.org.jocean.restfuldemo.bll.DemoResource
    parameters: |
      name=org.jocean.restfuldemo.bll.DemoResource
      before = 
      after = 
    children:
      - name: rpcs_sub.getCityByIpV2
        parameters: |
          name= getCityByIpV2
          before = logging
          after = retry.default, timeout.default
  - name: nettystats
  - name: jolokia
    parameters: |
      jolokia.port = 3020
  - name: jmxsrv
    parameters: |
      jmxmp.port = 0
      jmxhtml.port = 7321
  - name: service
    parameters: |
      demo.action=hi
  - name: statrest
  - name: cors
  - name: logrest
  - name: 100continue
  - name: bll
  - name: httpclient.default
    parameters: |
      http.client.thread.count = 2
      http.client.inbound.blocksize = 16384
      http.client.inbound.recvbuf = 16384
      http.client.outbound.sendbuf = 16384
      http.client.outbound.lowmark = 4096
      http.client.outbound.highmark = 16384
  - name: httpserver
    parameters: |
      # disable assembly
      # http.server.inbound.blocksize = 102400
      # set recv buffer size 8k
      http.server.inbound.recvbuf = 8192
      
      # work thread count
      http.server.work.thread.count=2
    children:
      - name: restin.9090
        parameters: |
          http.port = 9090
          http.address=0.0.0.0
          restin.pathpattern=/newrest/
          restin.category = demo
        children:
          - name: feature_logging
          - name: set_interceptor.demo
            parameters: |
              # Resource Class
              resource.class=org.jocean.restfuldemo.bll.DemoResource
              # interceptors (full class name) to attach
              resource.interceptors=\
              org.jocean.svr.interceptor.StatRest,\
              org.jocean.svr.interceptor.LogRest,\
              org.jocean.svr.interceptor.EnableCORS,\
              org.jocean.svr.interceptor.Handle100Continue
