name: units
parameters: |
  __spring.xml=http/httpserver.xml,jocean/eventengine.xml,http/httpclient.xml,http/signal.xml,unit/flowstats.xml,unit/apistats.xml
  # disable assembly
  http.server.inbound.blocksize = -1
  # set recv buffer size 8k
  http.server.inbound.recvbuf = 8192
children:
  - name: jolokia
    parameters: |
      jolokia.port = 3020
  - name: jmxsrv
    parameters: |
      jmxmp.port = 0
      jmxhtml.port = 7321
  - name: httpinbound.8080
    parameters: |
      http.port = 8080
      http.address=0.0.0.0
      inbound.pathpattern=/welcome/[{|}|/|\\w]*
      inbound.category=demo
    children:
      - name: feature_logging
  - name: regsignal_embed.outbound
    parameters: |
      req.class =org.jocean.restfuldemo.bean.outbound.OutboundRequest
      resp.class=org.jocean.restfuldemo.bean.outbound.OutboundResponse
      signal.uri=http://api.huaban.com
    children:
      - name: feature_logging
  - name: flowdemo
    parameters: |
      redirecturi.default=http://www.baidu.com/
    children:
      - name: ua2uri.wechat
        parameters: |
          ua=MicroMessenger
          uri=https://weixin.qq.com/
      - name: ua2uri.alipay
        parameters: |
          ua=AlipayClient
          uri=https://qr.alipay.com/ppx01048optiqycgvvhwpfc
  - name: service
    parameters: |
      demo.action=hi
  - name: statrest
  - name: cors
  - name: logrest
  - name: 100continue
  - name: bll2
  - name: restin.9090
    parameters: |
      http.port = 9090
      http.address=0.0.0.0
      restin.pathpattern=/newrest/[{|}|/|\\w]*
      restin.category = demo
    children:
      - name: feature_logging
      - name: set_interceptor.demo
        parameters: |
          # Resource Class
          resource.class=org.jocean.restfuldemo.bll2.DemoResource
          # interceptors (full class name) to attach
          resource.interceptors=\
          org.jocean.svr.interceptor.StatRest,\
          org.jocean.svr.interceptor.LogRest,\
          org.jocean.svr.interceptor.EnableCORS,\
          org.jocean.svr.interceptor.Handle100Continue
